name: personal_website
description: Richard Li's personal website
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_web_plugins:
    sdk: flutter
  fraction: ^4.1.4
  styled_widget:
    git:
      url: https://github.com/ReinBentdal/styled_widget.git

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
