name: personal_website
description: Richard Li's personal website
publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  boxy: ^2.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_web_plugins:
    sdk: flutter
  fraction: ^4.1.4
  go_router: ^6.0.9
  google_fonts: ^4.0.3
  styled_widget:
    git:
      url: https://github.com/ReinBentdal/styled_widget.git
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - content/skills/
    - content/works/
    - content/assets/
    - content/assets/works/
    - content/assets/skills/
